services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - form
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/FormData

  frontend:
    build: ./frontend
    ports:
      - "8001:8002"
    networks:
      - form
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: formdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - form
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

networks:
  form:
